id: I068DD0B0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T13:47:34+00:00'
last_modified: '2022-06-08T02:08:02.311451+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21659
  title: སྨན་སྦྱོར་ལག་ལེན་གྱི་གདམས་པ་མྱོང་གྲུབ་མ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    F62A:
      image_group_id: I4771
      title: ''
      total_pages: 300
      order: 1
      base_file: F62A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
